In [4]:
import numpy as np
import pandas as pd

matrix32 = np.array([[4, 5], [1, 2], [3, 6]])
matrix23 = np.array([[1, 4, 3], [2, 4, 5]])

print('3 x 2 matrix : \n', matrix32)
print('\n 2 x 3 matrix : \n', matrix23)

3 x 2 matrix : 
 [[4 5]
 [1 2]
 [3 6]]

 2 x 3 matrix : 
 [[1 4 3]
 [2 4 5]]


In [5]:
random_matrix = np.random.rand(3, 4)
print(random_matrix)

[[0.15144073 0.78724239 0.71075056 0.77853212]
 [0.78854763 0.88292123 0.45960432 0.48515122]
 [0.1423362  0.80665185 0.38257958 0.3952815 ]]


In [6]:
# matrix multiplication
matmul = np.dot(matrix32, matrix23)
print(matmul)

[[14 36 37]
 [ 5 12 13]
 [15 36 39]]


In [22]:
# elemet wise matrix multiplication
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5,6],[1,2,3]])
result=np.multiply(a,b)
print('Element wise Matrix Multiplication : \n', result)

Element wise multiplication : 
 [[ 4 10 18]
 [ 4 10 18]]


In [24]:
mat=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
mean = np.mean(mat)
print(mean)

5.0


In [27]:
data = pd.read_csv('mtcars.csv')

In [28]:
del data['model']

mean_center = data.apply(lambda e: e - e.mean())
print(mean_center.head())

        mpg     cyl        disp       hp      drat       wt     qsec      vs  \
0  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.59725 -1.38875 -0.4375   
1  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.34225 -0.82875 -0.4375   
2  2.709375 -2.1875 -122.721875 -53.6875  0.253437 -0.89725  0.76125  0.5625   
3  1.309375 -0.1875   27.278125 -36.6875 -0.516563 -0.00225  1.59125  0.5625   
4 -1.390625  1.8125  129.278125  28.3125 -0.446563  0.22275 -0.82875 -0.4375   

        am    gear    carb  
0  0.59375  0.3125  1.1875  
1  0.59375  0.3125  1.1875  
2  0.59375  0.3125 -1.8125  
3 -0.40625 -0.6875 -1.8125  
4 -0.40625 -0.6875 -0.8125  
