In [50]:
import numpy as np

In [51]:
X = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
Y = np.array([[56], 
                    [81], 
                    [119], 
                    [22], 
                    [103]], dtype='float32')

In [52]:
#Normalization
mu = np.mean(X, 0)
sigma = np.std(X, 0)
X = (X-mu) / sigma
X = np.hstack((np.ones((Y.size,1)),X))
print(X)

[[ 1.         -0.94528544 -0.61208051 -0.91202933]
 [ 1.          0.54727036  0.07897819  0.7680245 ]
 [ 1.          0.21559127  1.59272575  0.28800911]
 [ 1.          1.45938778 -1.40186191 -1.39204478]
 [ 1.         -1.27696455  0.34223863  1.24803984]]


In [53]:
#Obtaining random weight values
rng = np.random.default_rng(3)
w = rng.random((1, 4))
print(w)

[[0.08564917 0.23681051 0.80127447 0.58216204]]


In [54]:
def mse(mat1, mat2):
    diff = mat1 - mat2
    return np.sum(diff * diff) / diff.size

In [55]:
#row wise sigma(xi*wi)
def model(x,w):
    return x @ w.T

In [56]:
preds = model(X,w)
print(preds)
cost_initial = mse(preds, Y)
print("Cost before regression algo applied: ",cost_initial)

[[-1.15959769]
 [ 0.72564645]
 [ 1.58058189]
 [-1.50242425]
 [ 0.78403904]]
Cost before regression algo applied:  6899.795563150086


In [57]:
def gradient_descent(X, y, w, learning_rate, n_iters):
    J_history = np.zeros((n_iters,1))
    #print(J_history)
    for i in range(n_iters):
        h = model(X,w)
        #h=preds
        diff = h - y
        delta = (learning_rate/Y.size)*(X.T@diff)
        new_w = w - delta.T
        w=new_w
        J_history[i] = mse(h, y)
    return (J_history, w)

In [58]:
import matplotlib.pyplot as plt
n_iters = 1000
learning_rate = 0.01

#initial_cost = mse(model(X,w),Y)
cost_initial = mse(model(X,w),Y)

print("Initial cost is: ", initial_cost, "\n")

(J_history, optimal_weights) = gradient_descent(X, Y, w, learning_rate, n_iters)

print("Optimal values for weights are: \n", optimal_weights, "\n")

print("Final cost is: ", J_history[-1])

Initial cost is:  6899.795563150086 

Optimal values for weights are: 
 [[76.19671396 -4.55245529 25.36925536  9.18385576]] 

Final cost is:  [1.07012358]


In [59]:
preds = model(X,optimal_weights)
cost_final = mse(preds, Y)
# Print predictions
print("Prediction:\n",preds)
# Comparing predicted with targets
print("Targets:\n",Y)

Prediction:
 [[ 56.59611102]
 [ 82.76233422]
 [118.26654482]
 [ 21.20438518]
 [102.15419517]]
Targets:
 [[ 56.]
 [ 81.]
 [119.]
 [ 22.]
 [103.]]


In [60]:
print("Cost before regression algo applied: ",cost_initial)
print("Cost after linear regression algo applied: ",cost_final)

Cost before regression algo applied:  6899.795563150086
Cost after linear regression algo applied:  1.069503099980843
