In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

In [39]:
dataset = pd.read_csv("Dataset1.csv")
print(dataset)

   Outlook Temp Humidity Wind Play
0        R    H   Normal    F    N
1        R    H     High    T    N
2        O    H   Normal    F    Y
3        S    M   Normal    F    Y
4        S    C   Normal    F    Y
5        S    C      Low    T    N
6        O    C   Normal    T    Y
7        R    M   Normal    F    N
8        R    C      Low    F    Y
9        S    M     High    F    Y
10       R    M     High    T    Y
11       O    M      Low    T    Y
12       O    H   Normal    F    Y
13       S    M   Normal    T    N


In [40]:
label_encoder = preprocessing.LabelEncoder()
Y_rows=None
for data_heading in dataset:
  if data_heading!="Play":
    print(f"\n\nHeading :- {data_heading}")
    dummy = pd.get_dummies(dataset[data_heading])
    dataset = dataset.drop([data_heading],axis=1)
    dataset = pd.concat([dataset,dummy],axis=1)
  else:
    #print(dataset[data_heading])
    Y_rows = label_encoder.fit_transform(dataset[data_heading])
    print(Y_rows)
    dataset = dataset.drop([data_heading],axis=1)



Heading :- Outlook


Heading :- Temp


Heading :- Humidity


Heading :- Wind
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [41]:
print(dataset)
print (Y_rows)

    O  R  S  C  H  M  High  Low  Normal  F  T
0   0  1  0  0  1  0     0    0       1  1  0
1   0  1  0  0  1  0     1    0       0  0  1
2   1  0  0  0  1  0     0    0       1  1  0
3   0  0  1  0  0  1     0    0       1  1  0
4   0  0  1  1  0  0     0    0       1  1  0
5   0  0  1  1  0  0     0    1       0  0  1
6   1  0  0  1  0  0     0    0       1  0  1
7   0  1  0  0  0  1     0    0       1  1  0
8   0  1  0  1  0  0     0    1       0  1  0
9   0  0  1  0  0  1     1    0       0  1  0
10  0  1  0  0  0  1     1    0       0  0  1
11  1  0  0  0  0  1     0    1       0  0  1
12  1  0  0  0  1  0     0    0       1  1  0
13  0  0  1  0  0  1     0    0       1  0  1
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [69]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(dataset, Y_rows, test_size = 0.30, random_state = 3)

In [70]:
print(X_train)
print()
print(X_test)
print()
print(Y_train)
print(Y_test)

    O  R  S  C  H  M  High  Low  Normal  F  T
6   1  0  0  1  0  0     0    0       1  0  1
5   0  0  1  1  0  0     0    1       0  0  1
0   0  1  0  0  1  0     0    0       1  1  0
11  1  0  0  0  0  1     0    1       0  0  1
12  1  0  0  0  1  0     0    0       1  1  0
3   0  0  1  0  0  1     0    0       1  1  0
9   0  0  1  0  0  1     1    0       0  1  0
8   0  1  0  1  0  0     0    1       0  1  0
10  0  1  0  0  0  1     1    0       0  0  1

    O  R  S  C  H  M  High  Low  Normal  F  T
7   0  1  0  0  0  1     0    0       1  1  0
4   0  0  1  1  0  0     0    0       1  1  0
1   0  1  0  0  1  0     1    0       0  0  1
2   1  0  0  0  1  0     0    0       1  1  0
13  0  0  1  0  0  1     0    0       1  0  1

[1 0 0 1 1 1 1 1 1]
[0 1 0 1 0]


In [71]:
model = MultinomialNB()
model.fit(X_train, Y_train)
Y_predicted = model.predict(X_test)
print(X_test)
print(Y_predicted)

    O  R  S  C  H  M  High  Low  Normal  F  T
7   0  1  0  0  0  1     0    0       1  1  0
4   0  0  1  1  0  0     0    0       1  1  0
1   0  1  0  0  1  0     1    0       0  0  1
2   1  0  0  0  1  0     0    0       1  1  0
13  0  0  1  0  0  1     0    0       1  0  1
[1 1 1 1 1]


In [72]:
from sklearn import metrics

print(f"Accuracy is :- {metrics.accuracy_score(Y_test, Y_predicted)}")

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score


precision = precision_score(Y_test, Y_predicted)
recall = recall_score(Y_test, Y_predicted)


print(f"precision :- {precision}")
print(f"recall :- {recall}")

Accuracy is :- 0.4
precision :- 0.4
recall :- 1.0


In [73]:
#Outlook(O,R,S)=0  1  0,	Temp(C,H,M)=0  0  1,	Humidity(High,Low,Normal)=0  0 1,	Wind(F,T)=1,0,	Play=0
output = model.predict([[0,1,0, 0,0,1  ,0,0,1 ,1,0]])
print(f"final prediction :- {output}")

#Overcast , High, Normal, False
output = model.predict([[1,0,0  ,0,1,0    ,0,0,1  ,1,0]])
print(f"final prediction :- {output}")

# Overcast, Mild, Normal, True
output = model.predict([[1,0,0, 0,0,1 ,0,0,1  ,0,1]])
print(f"final prediction :- {output}")

# Sunny Cool High True
output = model.predict([[0,0,1, 1,0,0 ,1,0,0  ,0,1]])
print(f"final prediction :- {output}")


final prediction :- [1]
final prediction :- [1]
final prediction :- [1]
final prediction :- [1]
